Hw08 envdir tool
sitnikovik/otus-golang-professional pull request #8
Opened 2024-08-02 20:46 UTC by sitnikovik

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-08-03 05:24 UTC, ityulkanov commented on hw08_envdir_tool/executor.go
> +
вот тут забыли пробросить ещё stdIn

2024-08-03 05:26 UTC, ityulkanov commented on hw08_envdir_tool/executor.go
> +
и что то не нахожу копирования текущих переменных в новый слой, вроде такого: 
```
currentEnv := os.Environ()
c.Env = append([]string{}, currentEnv...)
```

2024-08-03 05:28 UTC, ityulkanov requested changes
Оставил парочку комментариев, посмотрите как будет время

2024-08-03 06:33 UTC, sitnikovik commented on hw08_envdir_tool/executor.go
> +
А для чего если задаем все переменные выше через `os.setEnv()` ?

2024-08-03 09:13 UTC, sitnikovik commented on hw08_envdir_tool/executor.go
> +
а для чего? os.Environ() вытащит все доступные переменные переменные.
Насколько я понял, команда должна прочитать значения из `testdata/` и добавить их в мапу `Environment`
Для проверки, что значение уже существует использую `os.Lookup()`

2024-08-09 08:53 UTC, ityulkanov commented on hw08_envdir_tool/executor.go
> +
Ну вообще предполагается что мы не только используем заданные нами значения, но и те что есть уже в системе (при этом перезаписывая заданные ранее если таковые имеются)

2024-08-09 08:55 UTC, ityulkanov commented on hw08_envdir_tool/executor.go
> +
Сейчас да, вы создаёте мапу со значениями, из testdata (ну либо из любой другой папки на выбор), которые вы используете дальше при исполнении самой программы, но программа может нуждаться и в других переменных окружения, тех что уже заданы в системе, а в новосозданном слое таких может не оказаться

2024-08-13 10:06 UTC, sitnikovik commented on hw08_envdir_tool/executor.go
> +
Исправил

2024-08-14 07:44 UTC, ityulkanov approved these changes

2024-08-14 16:49 UTC, merged